// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}

export { }
