// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Post: typeof import('./src/components/Post.vue')['default']
    PostsList: typeof import('./src/components/PostsList.vue')['default']
  }
}

export { }
